// Autogenerated by GenUnion.cs

using System.Runtime.CompilerServices;
using SpessaSharp.Utils;

namespace SpessaSharp.Synthesizer.Engine.Channel;

public record struct UserDrumParameter
{
    public const int Count = 4 + 1;
    
    [InlineArray(Count)]
    private struct Buffer { private float _element0; }
    private Buffer _buffer;

    public enum Type 
    {
        ///<summary>Rest of parameters of the User Drum Parameter</summary>
        DrumParameters,// DrumParameters.Entry
        ///<summary>The source drum set bank LSB number.</summary>
        SourceDrumSet,// int
        ///<summary>The source drum set bank LSB number.</summary>
        Program,// int
        ///<summary>The MIDI key number from the source drum set to bind.</summary>
        SourceNoteNumber,// int
    }
    
    // Set Get

    ///<summary>.</summary>
    public DrumParameter.Entry DrumParameters
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)] get =>
            GetDrumParameters_Entry(Type.DrumParameters);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] set =>
            Set(value);
    }

    ///<summary>.</summary>
    public int SourceDrumSet
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)] get =>
            GetInt(Type.SourceDrumSet);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] set =>
            Set(Type.SourceDrumSet, value);
    }

    ///<summary>.</summary>
    public int Program
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)] get =>
            GetInt(Type.Program);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] set =>
            Set(Type.Program, value);
    }

    ///<summary>.</summary>
    public int SourceNoteNumber
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)] get =>
            GetInt(Type.SourceNoteNumber);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] set =>
            Set(Type.SourceNoteNumber, value);
    }

    public static Params.Type TypeOf(Type type) => type switch
    {
        Type.DrumParameters => Params.Type.DrumParameters,
        Type.SourceDrumSet => Params.Type.Int,
        Type.Program => Params.Type.Int,
        Type.SourceNoteNumber => Params.Type.Int,
        _ => throw new ArgumentOutOfRangeException(nameof(type), type, null)
    };

    private static void Assert(Type type, Params.Type value) =>
        Params.Assert(TypeOf(type), value);
    
    // Entry
    public Entry this[Type type]
    {
        get => new(type, Params.Of(_buffer[(int)type]));
        set => _buffer[(int)value.Type] = value.Data.Value;
    }

    public readonly record struct Entry
    {
        public readonly Type Type;
        private readonly byte _extra;
        internal readonly Params.Data Data;
        
        internal Entry(Type type, Params.Data data, byte extra = 0)
        {
            Type = type;
            Data = data;
            _extra = extra;
        }
        
        public bool AsBool
        {
            get
            {
                Assert(Type, Params.Type.Bool);
                return Data.AsBool();
            }
        }

        public int AsInt
        {
            get
            {
                Assert(Type, Params.Type.Int);
                return Data.AsInt();
            }
        }

        public float AsFloat
        {
            get
            {
                Assert(Type, Params.Type.Float);
                return Data.AsFloat();
            }
        }
        
        public DrumParameter.Entry AsDrumParameter
        {
            get
            {
                Assert(Type, Params.Type.DrumParameters);
                return new DrumParameter.Entry((DrumParameter.Type)_extra, Data);
            }
        }
        
        public int ToInt() =>
            TypeOf(Type) switch
            {
                Params.Type.Int => Data.AsInt(),
                Params.Type.Float => (int)Data.AsFloat(),
                Params.Type.Bool => Data.AsBool() ? 1 : 0,
                Params.Type.DrumParameters => AsDrumParameter.ToInt(),
                Params.Type.InterpolationType or
                Params.Type.MidiSystem or
                Params.Type.CC or
                Params.Type.AssignMode or
                Params.Type.OptBool or
                Params.Type.OptInterpolationType or
                _ => throw new ArgumentOutOfRangeException()
            };

        private static Entry Of(Type type, float data) => 
            new(type, Params.Of(data));

        private static Entry Of(Type type, int data) =>
            new(type, Params.Of(data));

        private static Entry Of(Type type, bool data) =>
            new(type, Params.Of(data));
        
        private static Entry Of(DrumParameter.Entry drumParam) => 
            new(Type.DrumParameters, drumParam.Data, (byte)drumParam.Type);

        public static implicit operator Entry((Type Type, float Data) entry) =>
            Of(entry.Type, entry.Data);

        public static implicit operator Entry((Type Type, int Data) entry) =>
            Of(entry.Type, entry.Data);

        public static implicit operator Entry((Type Type, bool Data) entry) =>
            Of(entry.Type, entry.Data);
        
        public static implicit operator Entry(DrumParameter.Entry entry) =>
            Of(entry);
    }
    
    // Private
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private DrumParameter.Entry GetDrumParameters_Entry(Type type) =>
        new (
            (DrumParameter.Type)BitConverter.SingleToInt32Bits(_buffer[(int)type]), 
            Params.Of(_buffer[^1]));
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private float GetFloat(Type type) =>
        _buffer[(int)type];

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private int GetInt(Type type) =>
        BitConverter.SingleToInt32Bits(_buffer[(int)type]);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private bool GetBool(Type type) =>
        BitConverter.SingleToInt32Bits(_buffer[(int)type]) == 1;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void Set(Type type, float value) =>
        _buffer[(int)type] = value;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void Set(Type type, int value) =>
        _buffer[(int)type] = BitConverter.Int32BitsToSingle(value);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void Set(Type type, bool value) =>
        _buffer[(int)type] = BitConverter.Int32BitsToSingle(value ? 1 : 0);
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void Set(DrumParameter.Entry entry)
    {
        _buffer[(int)Type.DrumParameters] =
            BitConverter.Int32BitsToSingle((int)entry.Type);
        _buffer[^1] = entry.Data.Value;
    }
}

// Autogenerated by GenUnion.cs