// Autogenerated by GenUnion.cs

using System.Diagnostics;
using System.Runtime.CompilerServices;
using SpessaSharp.MIDI.Utils;
using SpessaSharp.Utils;

namespace SpessaSharp.Synthesizer.Engine.Channel;

public record struct UserDrumSetParameter
{
    public const int Count = 3 + 10; // DrumParameter count
    
    [InlineArray(Count)]
    private struct Buffer { private float _element0; }
    private Buffer _buffer;

    public enum Type 
    {
        ///<summary>Rest of parameters of the User Drum Parameter</summary>
        DrumParameters,// DrumParameters.Entry
        ///<summary>The source drum set bank LSB number.</summary>
        SourceDrumSet,// int
        ///<summary>The source drum set bank LSB number.</summary>
        Program,// int
        ///<summary>The MIDI key number from the source drum set to bind.</summary>
        SourceNoteNumber,// int
    }
    
    // Set Get

    ///<summary>.</summary>
    public DrumParameter DrumParameters
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
        {
            var result = 
                DrumParameter.Default;

            for (var i = 3; i < Count; i++)
            {
                var type = (DrumParameter.Type)(i - 3); 
                var data = new DrumParameter.Entry(
                    type, Params.Of(_buffer[i]));
                result[type] = data;
            }
        
            return result;   
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set
        {
            for (var i = 3; i < Count; i++)
            {
                var type = (DrumParameter.Type)(i - 3);
                var entry = value[type];
                _buffer[i] = entry.Data.Value;
            }
        }
    }

    public DrumParameter.Entry GetDrumParameter(DrumParameter.Type type) =>
        new(type, Params.Of(_buffer[(int)type + 3]));

    public void SetDrumParameter(DrumParameter.Entry value)
    {
        var i = (int)value.Type + 3;
        _buffer[i] = value.Data.Value;
    }

    ///<summary>.</summary>
    public int SourceDrumSet
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)] get =>
            GetInt(Type.SourceDrumSet);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] set =>
            Set(Type.SourceDrumSet, value);
    }

    ///<summary>.</summary>
    public int Program
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)] get =>
            GetInt(Type.Program);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] set =>
            Set(Type.Program, value);
    }

    ///<summary>.</summary>
    public int SourceNoteNumber
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)] get =>
            GetInt(Type.SourceNoteNumber);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] set =>
            Set(Type.SourceNoteNumber, value);
    }

    internal void CopyTo(Span<Entry> array)
    {
        Debug.Assert(array.Length <= Count);
        for (var i = 0; i < Count; i++)
            array[i] =
                i <= 3 
                ? new Entry((Type)i, Params.Of(_buffer[i]))
                : new DrumParameter.Entry(
                    (DrumParameter.Type)i - 3, Params.Of(_buffer[i]));
    }

    public static Params.Type TypeOf(Type type) => type switch
    {
        Type.DrumParameters => Params.Type.DrumParameters,
        Type.SourceDrumSet => Params.Type.Int,
        Type.Program => Params.Type.Int,
        Type.SourceNoteNumber => Params.Type.Int,
        _ => throw new ArgumentOutOfRangeException(nameof(type), type, null)
    };

    private static void Assert(Type type, Params.Type value) =>
        Params.Assert(TypeOf(type), value);
    
    // Entry
    public Entry this[Type type]
    {
        get => new(type, Params.Of(_buffer[(int)type]));
        set => _buffer[(int)value.Type] = value.Data.Value;
    }

    public static readonly UserDrumSetParameter Default = new ()
    {
        DrumParameters = 
            DrumParameter.Default,
        SourceDrumSet = 0,
        SourceNoteNumber = 0,
        Program = 0,
    };

    public readonly record struct Entry
    {
        public readonly Type Type;
        private readonly byte _extra;
        internal readonly Params.Data Data;
        
        internal Entry(Type type, Params.Data data, byte extra = 0)
        {
            Type = type;
            Data = data;
            _extra = extra;
        }

        public int AsInt
        {
            get
            {
                Assert(Type, Params.Type.Int);
                return Data.AsInt();
            }
        }

        public DrumParameter.Entry AsDrumParameter
        {
            get
            {
                Assert(Type, Params.Type.DrumParameters);
                return new DrumParameter.Entry((DrumParameter.Type)_extra, Data);
            }
        }
        
        public int ToInt() =>
            TypeOf(Type) switch
            {
                Params.Type.Int => Data.AsInt(),
                Params.Type.Float => (int)Data.AsFloat(),
                Params.Type.Bool => Data.AsBool() ? 1 : 0,
                Params.Type.DrumParameters => AsDrumParameter.ToInt(),
                Params.Type.InterpolationType or
                Params.Type.MidiSystem or
                Params.Type.CC or
                Params.Type.AssignMode or
                Params.Type.OptBool or
                Params.Type.OptInterpolationType or
                _ => throw new ArgumentOutOfRangeException()
            };

        private static Entry Of(Type type, float data) => 
            new(type, Params.Of(data));

        private static Entry Of(Type type, int data) =>
            new(type, Params.Of(data));

        private static Entry Of(Type type, bool data) =>
            new(type, Params.Of(data));
        
        private static Entry Of(DrumParameter.Entry drumParam) => 
            new(Type.DrumParameters, drumParam.Data, (byte)drumParam.Type);

        public static implicit operator Entry((Type Type, float Data) entry) =>
            Of(entry.Type, entry.Data);

        public static implicit operator Entry((Type Type, int Data) entry) =>
            Of(entry.Type, entry.Data);

        public static implicit operator Entry((Type Type, bool Data) entry) =>
            Of(entry.Type, entry.Data);
        
        public static implicit operator Entry(DrumParameter.Entry entry) =>
            Of(entry);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private int GetInt(Type type) =>
        BitConverter.SingleToInt32Bits(_buffer[(int)type]);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void Set(Type type, int value) =>
        _buffer[(int)type] = BitConverter.Int32BitsToSingle(value);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void Set(Type type, bool value) =>
        _buffer[(int)type] = BitConverter.Int32BitsToSingle(value ? 1 : 0);
}

// Autogenerated by GenUnion.cs