blank_issues_enabled: false
contact_links:
    - name: "Question"
      url: "https://github.com/Wh1teDuke/SpessaSharp/discussions/new?category=q-a"
      about: "Something is unclear? Ask a question!"
    - name: "Documentation"
      url: "https://wh1teduke.github.io/SpessaSharp/"
      about: "Visit the complete API documentation!"
