#!/usr/bin/env -S dotnet run

var argsStart = 0;
var genEntry = false;

for (; argsStart < args.Length; argsStart++)
{
    var arg = args[argsStart];
    if (!arg.StartsWith("--")) break;

    switch (arg)
    {
        case "--entry":
            genEntry = true;
            break;
    }
}

var structName = args[argsStart++];

var result = args[argsStart..]
    .Select(arg => arg.Split(':', StringSplitOptions.TrimEntries))
    .Where(group => group.Length > 0)
    .ToList();

var types = new List<(string Name, string Type, string Description)>();
foreach (var arg in result)
{
    if (arg is not [var name, var type, var desc])
        throw new ArgumentException("GenUnion.cs <struct_name> [tname:ttype:tdesc]...");

    types.Add((name, type, desc));
}

var enumData = "";
foreach (var (name, type, desc) in types)
{
    enumData += $"        ///<summary>{desc}.</summary>\n";
    enumData += $"        {name},// {type}\n";
}
enumData = enumData.TrimEnd('\n');

var typeCheck = "";
foreach (var (name, type, _) in types)
{
    var cType =
        System.Globalization.CultureInfo
            .CurrentCulture.TextInfo.ToTitleCase(type.ToLower());
    if (type is not ("int" or "float" or "bool"))
        cType = name;
    typeCheck += $"        Type.{name} => Params.Type.{cType},\n";
}
typeCheck = typeCheck.TrimEnd('\n');

var setget = "\n";
foreach (var (name, type, desc) in types)
{
    var cType = 
        System.Globalization.CultureInfo
            .CurrentCulture.TextInfo.ToTitleCase(type.ToLower());
    
    var retType = type;
    if (type is not ("float" or "bool" or "int"))
    {
        cType = type;
    }
    
    setget += 
    string.Format(
"""
    ///<summary>{0}.</summary>
    public {3} {1}
    {{
        [MethodImpl(MethodImplOptions.AggressiveInlining)] get =>
            Get{2}(Type.{1});
        [MethodImpl(MethodImplOptions.AggressiveInlining)] set =>
            Set(Type.{1}, value);
    }}
""", desc, name, cType, retType);
    setget += "\n\n";
}
setget = setget.TrimEnd('\n');

var entry = "";
if (genEntry)
{
    entry =
"""
    public Entry this[Type type]
    {
        get => new(type, Params.Of(_buffer[(int)type]));
        set => _buffer[(int)value.Type] = value.Data.Value;
    }

    public readonly record struct Entry
    {
        public readonly Type Type;
        internal readonly Params.Data Data;
        
        internal Entry(Type type, Params.Data data)
        {
            Type = type;
            Data = data;
        }
        
        public bool AsBool
        {
            get
            {
                Assert(Type, Params.Type.Bool);
                return Data.AsBool();
            }
        }

        public int AsInt
        {
            get
            {
                Assert(Type, Params.Type.Int);
                return Data.AsInt();
            }
        }

        public float AsFloat
        {
            get
            {
                Assert(Type, Params.Type.Float);
                return Data.AsFloat();
            }
        }

        private static Entry Of(Type type, float data) => 
            new(type, Params.Of(data));

        private static Entry Of(Type type, int data) =>
            new(type, Params.Of(data));

        private static Entry Of(Type type, bool data) =>
            new(type, Params.Of(data));

        public static implicit operator Entry((Type Type, float Data) entry) =>
            Of(entry.Type, entry.Data);

        public static implicit operator Entry((Type Type, int Data) entry) =>
            Of(entry.Type, entry.Data);

        public static implicit operator Entry((Type Type, bool Data) entry) =>
            Of(entry.Type, entry.Data);
    }
""";
}


// ----------------------------------------------------------------------------
var str = """
// Autogenerated by GenUnion.cs

using System.Runtime.CompilerServices;
using SpessaSharp.Utils;

public record struct {0}
{{
    public const int Count = {1};
    
    [InlineArray(Count)]
    private struct Buffer {{ private float _element0; }}
    private Buffer _buffer;

    public enum Type 
    {{
{2}
    }}
    
    // Set Get
{3}

    public static Params.Type TypeOf(Type type) => type switch
    {{
{4}
        _ => throw new ArgumentOutOfRangeException(nameof(type), type, null)
    }};

    private static void Assert(Type type, Params.Type value) =>
        Params.Assert(TypeOf(type), value);
    
    // Entry
{5}
    
    // Private
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private float GetFloat(Type type) =>
        _buffer[(int)type];

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private int GetInt(Type type) =>
        BitConverter.SingleToInt32Bits(_buffer[(int)type]);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private bool GetBool(Type type) =>
        BitConverter.SingleToInt32Bits(_buffer[(int)type]) == 1;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void Set(Type type, float value) =>
        _buffer[(int)type] = value;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void Set(Type type, int value) =>
        _buffer[(int)type] = BitConverter.Int32BitsToSingle(value);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void Set(Type type, bool value) =>
        _buffer[(int)type] = BitConverter.Int32BitsToSingle(value ? 1 : 0);
}}

// Autogenerated by GenUnion.cs
""";

str = string.Format(
    str, structName, types.Count, enumData, setget, typeCheck, entry);

File.WriteAllText(structName + ".cs", str);