name: Publish SpessaSharp NuGet

on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: nuget-publish
    permissions:
      contents: read
      id-token: write
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Pack
        run: dotnet pack SpessaSharp/SpessaSharp.csproj --output ./nupkg

      - name: Push to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate
